import sqlite3
import os
import datetime

DB_PATH = 'violations.db'

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Create the students table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS students (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_name TEXT NOT NULL,
            usn TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE NOT NULL,
            user_id TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            face_embedding TEXT,
            face_image_path TEXT,
            registration_time TEXT NOT NULL,
            is_active BOOLEAN DEFAULT 1
        )
    ''')
    
    # Create the admins table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS admins (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            admin_id TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL
        )
    ''')
    
    # Seed or repair default admin
    cursor.execute('SELECT password_hash FROM admins WHERE admin_id = ?', ('admin',))
    row = cursor.fetchone()
    
    # pyrefly: ignore [missing-import]
    import bcrypt
    needs_seeding = False
    if not row:
        needs_seeding = True
    elif not row['password_hash'].startswith('$2b$'):
        # Delete invalid hash generated by werkzeug
        cursor.execute('DELETE FROM admins WHERE admin_id = ?', ('admin',))
        needs_seeding = True
        
    if needs_seeding:
        salt = bcrypt.gensalt()
        hashed = bcrypt.hashpw('admin123'.encode('utf-8'), salt).decode('utf-8')
        cursor.execute('''
            INSERT INTO admins (admin_id, password_hash) VALUES (?, ?)
        ''', ('admin', hashed))
    
    try:
        cursor.execute('ALTER TABLE students ADD COLUMN face_image_path TEXT')
    except sqlite3.OperationalError:
        pass
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS exam_sessions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            student_id INTEGER NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT,
            video_path TEXT,
            FOREIGN KEY(student_id) REFERENCES students(id)
        )
    ''')
    
    # Create the violations table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS violations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            violation_type TEXT NOT NULL,
            evidence_path TEXT,
            details TEXT
        )
    ''')
    
    try:
        cursor.execute('ALTER TABLE violations ADD COLUMN evidence_path TEXT')
    except sqlite3.OperationalError:
        pass
        
    try:
        cursor.execute('ALTER TABLE violations ADD COLUMN details TEXT')
    except sqlite3.OperationalError:
        pass
        
    # Create the reports table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS exam_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            summary TEXT NOT NULL
        )
    ''')
    
    try:
        cursor.execute('ALTER TABLE violations ADD COLUMN session_id INTEGER')
    except sqlite3.OperationalError:
        pass
        
    try:
        cursor.execute('ALTER TABLE violations ADD COLUMN relative_timestamp REAL')
    except sqlite3.OperationalError:
        pass
    try:
        cursor.execute('ALTER TABLE exam_sessions ADD COLUMN fps REAL DEFAULT 0.0')
        cursor.execute('ALTER TABLE exam_sessions ADD COLUMN camera_uptime REAL DEFAULT 0.0')
        cursor.execute('ALTER TABLE exam_sessions ADD COLUMN face_visibility_pct REAL DEFAULT 0.0')
        cursor.execute('ALTER TABLE exam_sessions ADD COLUMN screen_focus_pct REAL DEFAULT 0.0')
        cursor.execute('ALTER TABLE exam_sessions ADD COLUMN audio_activity_pct REAL DEFAULT 0.0')
    except sqlite3.OperationalError:
        pass
        
    print("Admin account verified successfully")
    conn.commit()
    conn.close()

def log_violation(violation_type, evidence_path=None, details="", session_id=None, relative_timestamp=None):
    """
    Store every violation with timestamp and evidence image/audio.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    cursor.execute('''
        INSERT INTO violations (session_id, timestamp, relative_timestamp, violation_type, evidence_path, details)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (session_id, timestamp, relative_timestamp, violation_type, evidence_path, details))
    
    conn.commit()
    conn.close()

def get_timeline(limit=50):
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT timestamp, violation_type, details FROM violations ORDER BY timestamp DESC LIMIT ?', (limit,))
    rows = cursor.fetchall()
    conn.close()
    
    SEVERITY_MAP = {
        "Mobile Phone Detected": "HIGH",
        "Multiple Persons Detected": "HIGH",
        "Identity Mismatch": "CRITICAL",
        "Face Absent": "MEDIUM",
        "Looking Away From Exam Screen": "LOW",
        "Tab Switch Detected": "MEDIUM",
        "Fullscreen Violation": "MEDIUM",
        "Multiple Voices Detected": "HIGH",
        "External Audio Detected": "HIGH",
        "Restricted Key Attempt": "MEDIUM",
        "Browser Manipulation Detected": "MEDIUM",
        "Right Click Attempt": "MEDIUM"
    }
    
    timeline = []
    for row in rows:
        base_type = row["violation_type"]
        severity = SEVERITY_MAP.get(base_type, "MEDIUM")
        typ = f"[{severity}] {base_type}"
        if row["details"]:
            typ = f"{typ} ({row['details']})"
        timeline.append({"timestamp": row["timestamp"], "type": typ})
    return timeline

def save_report_summary(summary):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO exam_reports (timestamp, summary)
        VALUES (?, ?)
    ''', (timestamp, summary))
    conn.commit()
    conn.close()

def get_latest_report_summary():
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT summary FROM exam_reports ORDER BY id DESC LIMIT 1')
    row = cursor.fetchone()
    conn.close()
    return row['summary'] if row else "No AI summary has been generated yet."

if __name__ == "__main__":
    init_db()
    print("Database violations.db initialized.")
